### PR TITLE
Add support for Master world saving

### PR DESCRIPTION
**Pull request by RemcoSpigot**
- Added support for defining volumes and pvcs for the master server

### CODE REVIEW

**Review by 1lann — APPROVED** [review]
LGTM, I'm not sure though about why the_end and the nether are seperate, are they not DIM-1/DIM1 or whatever subfolders in the world directory?

**Comment by 1lann** [comment]
I personally would just want the entire server directory as a single persistent volume so `/op`, etc. works.

**Comment by RemcoSpigot** [comment]
> I personally would just want the entire server directory as a single persistent volume so `/op`, etc. works.

This would be great. However for this to work the world folders would have to be in a sub directory relative to the work directory of the container. Otherwise if we would make the entire work directory a volume, it would override the contents and remove the JAR along with it.

**Comment by 1lann** [comment]
Alright, the way I did it in my spec was keep the jar outside of the work folder, and make the entire work folder a volume (i.e. the server runs fine even if the jar is outside of the current directory, it will still store everything in the current directory!)

**Pull request merged**
